title: Polly Ho | Blog
description: Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pinyuho.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Polly Ho
author-image:   1.jpg
author-job:     NTUIM
author-email:   polly@ntu.im # Add your email for contant form.
author-twitter:  # Add your twitter account
about-author:   雜草叢生的生活筆記。

# Social settings
social-twitter:   
social-facebook:  
social-github:    pinyuho
social-pinterest:
social-instagram: 
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
